# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  ituminitwit:
    image: ituminitwit
    build: 
      context: .
      dockerfile: 'MiniTwit/MiniTwit.Server/Dockerfile'
    ports:
      - 5000:5000
  ituminitwitweb:
    image: ituminitwitweb
    build:
      context: .
      dockerfile: 'MiniTwit/MiniTwit.Web/Dockerfile'
    ports:
      - "3000:3000"
