version: '3.4'

networks:
  main:
    name: itu-minitwit-monitoring

services:
  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./Monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_storage:/prometheus
      ports:
        - "9090:9090"
      networks:
        - main

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      GF_SECURITY_ADMIN_USER: radiator
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_SERVER_HTTP_PORT: 3001
    volumes:
      - ./Monitoring/grafana.yml:/etc/grafana/provisioning/datasources/grafana.yml
      - grafana_storage:/var/lib/grafana
    ports:
      - "9091:3001"
    depends_on:
      - prometheus
    networks:
      - main

volumes:
  grafana_storage:
  prometheus_storage:
