# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      MONGO_INITDB_ROOT_USERNAME: radiator
      MONGO_INITDB_ROOT_PASSWORD_FILE: run/secrets/db_password
      MONGO_INITDB_DATABASE: MiniTwit
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - '27018:27017'
    secrets:
      - db_password

  itu-minitwit-server:
    image: itu-minitwit-server
    build: 
      context: .
      dockerfile: 'MiniTwit.Server/Dockerfile'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__MiniTwit:
    ports:
      - '80:80'
    depends_on:
      - mongodb
    secrets:
      - source: connection_string
        target: ConnectionStrings__MiniTwit

  itu-minitwit-web:
    image: itu-minitwit-web
    build:
      context: .
      dockerfile: 'MiniTwit.Web/Dockerfile'
    ports:
      - '3000:3000'
    depends_on:
      - itu-minitwit-server

volumes:
  mongodb_data_container:

secrets:
  db_password:
    file: './.local/db_password.txt'
  connection_string:
    file: './.local/connection_string.txt'
