version: '3.4'

networks:
  main:
    name: itu-minitwit-monitoring

services:
  prometheus:
      image: prom/prometheus:latest
      volumes:
        - ./Monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_storage:/prometheus
      ports:
        - "9090:9090"
      networks:
        - main

  grafana:
    image: grafana/grafana:latest
    environment:
      GF_SECURITY_ADMIN_USER: radiator
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/grafana_password
    volumes:
      - ./Monitoring/grafana.yml:/etc/grafana/provisioning/datasources/grafana.yml
      - grafana_storage:/var/lib/grafana
    ports:
      - "9091:3000"
    depends_on:
      - prometheus
    networks:
      - main
    secrets:
    - grafana_password

volumes:
  grafana_storage:
  prometheus_storage:

secrets:
  grafana_password:
    file: './.local/grafana_password.txt'
