version: '3.4'

networks:
  elk:
    name: itu-minitwit-logging

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    environment:
        - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
        - "discovery.type=single-node"
        - "xpack.security.enabled=false"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    environment:
        - "elasticsearch.hosts='[\"http://elasticsearch:9200\"]'"
        - "xpack.security.enabled=false"
    volumes:
        - kibana-data:/usr/share/kibana/data
    networks:
      - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.9
    environment:
      - "ELK_USER=${ELK_USER}"
    user: root
    volumes:
      - ${ELK_DIR}/Logging/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - elk

  nginx:
      image: nginx:latest
      ports:
        - 9200:9200
        - 5601:5601
        - 8881:8881
        - 8882:8882
      networks:
        - elk
      volumes:
        - type: bind
          source: ${ELK_DIR}/Logging/nginx.conf
          target: /etc/nginx/nginx.conf
        - type: bind
          source: ${ELK_DIR}/Logging/.htpasswd
          target: /etc/nginx/.htpasswd

volumes:
  elasticsearch-data:
  kibana-data: