version: '3.4'

services:
    test-database:
      image: 'postgres:latest'
      ports:
        - '5433:5432'
      environment:
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        POSTGRES_DB: 'test'
        # Test