version: '3.4'

networks:
  main:
    driver: overlay
    ipam:
      config:
        - subnet: 192.168.18.0/24

services:
  itu-minitwit-server:
    image: ${DOCKER_USERNAME}/itu-minitwit-server:latest
    container_name: minitwit
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:80
      ConnectionStrings__MiniTwit: ${DB_CONNECTION_STRING}
    deploy:
      replicas: 2
      update_config:
        delay: 10s
    ports:
      - '80:80'
    networks:
      - main
    depends_on:
      - mongodb

  itu-minitwit-web:
    image: ${DOCKER_USERNAME}/itu-minitwit-web:latest
    deploy:
      replicas: 2
      update_config:
        delay: 10s
    ports:
      - '3000:3000'
    networks:
      - main
    depends_on:
      - itu-minitwit-server
