# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=radiator
      - MONGO_INITDB_ROOT_PASSWORD=TqqW1zCn3XO2r0vkjjy5g1Y7AjWxOt
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - '27017:27017'

  itu-minitwit-server:
    image: itu-minitwit-server
    build: 
      context: .
      dockerfile: 'MiniTwit.Server/Dockerfile'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:80
    ports:
      - '80:80'
    depends_on:
      - mongodb

  itu-minitwit-web:
    image: itu-minitwit-web
    build:
      context: .
      dockerfile: 'MiniTwit.Web/Dockerfile'
    ports:
      - '3000:3000'
    depends_on:
      - itu-minitwit-server

volumes:
  mongodb_data_container:
