# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONDO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    ports:
      - '27017:27017'

  ituminitwit:
    image: ituminitwit
    build: 
      context: .
      dockerfile: 'MiniTwit/MiniTwit.Server/Dockerfile'
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
    ports:
      - '8080:8080'
    depends_on:
      - mongodb

  ituminitwitweb:
    image: ituminitwitweb
    build:
      context: .
      dockerfile: 'MiniTwit/MiniTwit.Web/Dockerfile'
    ports:
      - '3000:3000'
  