name: Build / Test

on: 
  [push]

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build MiniTwit backend
        run: dotnet build --no-restore

      - name: Run backend tests
        run: dotnet test --no-build --verbosity normal
