name: Build / Test

on: 
  pull_request:
    branches: [main]
env: 
  NODE_ENV: development

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build MiniTwit backend
        run: dotnet build --no-restore

      - name: Run backend tests
        run: dotnet test --no-build --verbosity normal
  
  UITest:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: setUp NodeJS
        uses: actions/setup-node@master
        with:
          node-version: 18
      - name: Run Tests
        run: | 
          echo "hello world"
          mkdir .local
          echo ${{secrets.DB_CONNECTIONSTRING}} > .local/connection_string.txt
          echo ${{secrets.DB_PASSWORD}} > .local/db_password.txt
          docker-compose up -d
          docker ps
          docker images
          docker-compose down



          
       



