---
name: Continuous Deployment

on:
  push:
    # Run workflow every time something is pushed to the main branch
    branches:
      - main
      - master
  # allow manual triggers for now too
  workflow_dispatch:
    manual: true


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Deploy to production
        uses: fifsky/ssh-action@master
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USER: ${{ secrets.SSH_USERNAME }}
          KEY: ${{ secrets.SSH_KEY }}
          SSH_PASSPHRASE: ${{secrets.SSH_PASSPHRASE}}
          command: |
            git pull


