---
name: Continuous Deployment

on:
  push:
    # Run workflow every time something is pushed to the main branch
    branches:
      - main
      - master
  # allow manual triggers for now too
  workflow_dispatch:
    manual: true


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push itu-minitwit-server
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./MiniTwit.Server/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/itu-minitwit-server

      - name: Build and push itu-minitwit-web
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./MiniTwit.Web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/itu-minitwit-web
          
      - name: Deploy
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          args: "-vvv"
          command: |
            cd itu-minitwit/
            git pull
            docker pull ${{ secrets.DOCKER_USERNAME }}/itu-minitwit-web
            docker pull ${{ secrets.DOCKER_USERNAME }}/itu-minitwit-server
            docker-compose down
            docker-compose up -d

