name: Swarm Deployment

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy docker-compose files to Swarm Manager
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avz --delete --include="docker-compose.*.yml" --exclude="*"
          path: .
          remote_path: ./itu-minitwit/
          remote_host: ${{ secrets.SSH_HOST_SWARM }}
          remote_user: ${{ secrets.SSH_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
